# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

  - task: SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: hugolamounier
      projectKey: 'hugolamounier_Thoth'
      projectName: Thoth

  - task: CmdLine@2
    displayName: Begin scan
    inputs:
      script: |
        dotnet sonarscanner begin /k:"hugolamounier_Thoth" /d:sonar.login="$(TOKEN)" /o:"hugolamounier" /d:sonar.cs.opencover.reportsPaths="**/*/coverage.opencover.xml"

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: CmdLine@2
    displayName: Run containers
    inputs:
      script: |
        docker compose up -d sqlserver --build

  - task: DotNetCoreCLI@2
    displayName: 'Test applicaiton'
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --logger trx --settings "./runsettings.xml"'

  - task: SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'

  - task: CmdLine@2
    displayName: 'Publish Coverage Result'
    inputs:
      script: |
        dotnet sonarscanner end /d:sonar.login="$(TOKEN)"