FROM mcr.microsoft.com/dotnet/sdk:6.0

RUN dotnet tool install --global dotnet-sonarscanner
RUN dotnet sonarscanner begin /k:"hugolamounier_Thoth" /o:"hugolamounier" /d:sonar.login="<token>"

WORKDIR /app
COPY . ./
RUN chmod -R 755 ./Scripts