version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: Password1
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  
  integration-tests:
    container_name: integration-tests
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .env
    depends_on:
      - sqlserver
    command: [ "./Scripts/start-tests.sh" ]