name: PR Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/hugolamouniersoft/Hugo
          azure-pipeline-name: 'Thoth'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}